### ISSUE TITLE
Node start command should use Tini

### ISSUE THREAD

**Issue by kvedurmu** [paketo-buildpacks/node-start#16]
I was playing around with the latest language family Node.js buildpack (which adds the node-engine, node-start) group and it seems like basic Node apps (without a package manager) don't support graceful shutdown. Could we consider adding tini to this group and modifying node-start start command?

I'm just building this [app](https://github.com/paketo-buildpacks/node-engine/tree/main/integration/testdata/simple_app) with the language family buildpack (gcr.io/paketo-buildpacks/nodejs). I'm running the container in the foreground and using `CTRL^C` to stop the container, but it just hangs. 

[Slack thread](https://paketobuildpacks.slack.com/archives/CUD6R3CPL/p1597330819004600) for more context

**Comment by ryanmoran** [comment]
This is the expected behavior.

The kernel keeps a table of signal handlers for all processes and forwards those signals when they occur. In this case, you are typing `CTRL^C` at the keyboard which causes the terminal to send `SIGINT` to the process. The kernel sees that the `node` process has not registered its own signal handler for the `SIGINT` process and thus performs the default which is to terminate the process.

However, when we run `node` inside your app container, we are running the `node` process as PID1. PID1 is special when it comes to signal handling. The kernel will not terminate the PID1 process when it receives `SIGINT`, like it would for other processes. Instead, it expects the PID1 process to have registered a signal handler for `SIGINT` and terminate itself.

Application developers should understand that `node` is running as PID1 in the container and include signal handlers like the following to handle graceful shutdown:
```javascript
process.on('SIGINT', () => {
  console.log("exiting");
  process.exit(0);
});
```

We can document this, but it is pretty commonly understood in the community of developers running `node` inside containers.

**Comment by kvedurmu** [comment]
Thanks for clarifying, closing this. No need to document this since it's common behavior.

**Comment by arjun024** [comment]
Just to add to this, the nodejs buildpack does not force the user to run the image as PID 1. A user can demote the node process by using docker's built-in tini as the init process, then get node to do the default SIGINT action to work fine if they so wish.

```
$ docker run -p 8080:8080 --init mynodeapp
server is listening on 8080
^C
```
